Create gsso.yml
OBOFoundry/purl.obolibrary.org pull request #692
Opened 2020-10-01 17:46 UTC by matentzn

@Superraptor

2020-10-01 17:55 UTC, jamesaoverton requested changes

2020-10-01 17:55 UTC, jamesaoverton commented on config/gsso.yml
> +- exact: /
Apache matched entries in order. This `exact: /` entry will never be matched, because the previous `prefix: /` hides it.

2020-10-01 18:21 UTC, jamesaoverton approved these changes

2020-10-01 18:29 UTC, merged

2020-10-02 14:46 UTC, Superraptor reviewed
Everything appears to be in order! Thank you so much!